### PR TITLE
Added netbox lookup plugin (#26)

### PR DESCRIPTION
**Pull request by cpmills1975**
A first attempt to include my Netbox lookup plugin. I've attempted to write some integration tests and they appear to pass when I use a similarly configured Netbox container.

### CODE REVIEW

**Comment by cpmills1975** [comment]
Hmm. Looks like all integration tests are failing in travis due to a 502 error talking to Netbox.

**Comment by FragmentedPacket** [comment]
I looked into it a little bit last night and got it working with a longer sleep. There was a new release of netbox-docker that most likely caused this. I'll try and get something pushed up this weekend, but I'm traveling at the moment so hopefully fix this.

You can try editing the .travis.yml and where sleep is 60, try changing it to 120.

**Comment by FragmentedPacket** [comment]
Thanks for making those changes. I think I will get this merged in and work on the CI/CD stuff soon since it seems to pass with Netbox 2.6. I'll tag you in any issues that arise from the lookup plugin and I'll add unit and more integration tests at a later point as well.

**Comment by cpmills1975** [comment]
> Thanks for making those changes. I think I will get this merged in and work on the CI/CD stuff soon since it seems to pass with Netbox 2.6. I'll tag you in any issues that arise from the lookup plugin and I'll add unit and more integration tests at a later point as well.

Thank you. It seems that the Netbox 2.5 failures are due to the docker image itself. Netbox throws an exception shortly after starting...

...
netbox_1         | ⚙️ Executing '/opt/netbox/startup_scripts/220_prefixes.py'
netbox_1         | ⚙️ Executing '/opt/netbox/startup_scripts/230_virtual_machines.py'
netbox_1         | ⚙️ Executing '/opt/netbox/startup_scripts/240_virtualization_interfaces.py'
netbox_1         | ⚙️ Executing '/opt/netbox/startup_scripts/250_dcim_interfaces.py'
netbox_1         | Traceback (most recent call last):
netbox_1         |   File "./manage.py", line 10, in <module>
netbox_1         |     execute_from_command_line(sys.argv)
netbox_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
netbox_1         |     utility.execute()
netbox_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
netbox_1         |     self.fetch_command(subcommand).run_from_argv(self.argv)
netbox_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
netbox_1         |     self.execute(*args, **cmd_options)
netbox_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
netbox_1         |     output = self.handle(*args, **options)
netbox_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/shell.py", line 92, in handle
netbox_1         |     exec(sys.stdin.read())
netbox_1         |   File "<string>", line 2, in <module>
netbox_1         | ImportError: cannot import name 'IFACE_TYPE_CHOICES'


I'll be interested in how to put together unit tests - it's not something I have any experience of.

**Comment by FragmentedPacket** [comment]
Yes! I was troubleshooting that while I was at the airport this morning and in the process of submitting a ticket to the netbox-docker repo but then had to board. I got around it by changing the `env/netbox` SKIP_STARTUP_SCRIPTS=true.

I'll ping you once I have the tests wrote but may not be for a few weeks possibly

**Pull request merged**
